--[[
    Nexus Vision - Generated Roblox UI Library
    ==========================================
    Generated from: Screenshot Analysis
    Theme: dark
    Elements detected: 1
    Confidence: 0%
    
    This library was automatically generated by Nexus Vision.
    It recreates the UI elements detected in the uploaded screenshot.
]]

local Library = {
    Version = "1.0.0",
    Theme = {},
    Flags = {},
    Registry = {},
    Elements = {},
    Connections = {},
    Animations = {},
}

--[=[ Service Caches ]=]
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

--[=[ Utility Functions ]=]

function Library:Round(number, decimals)
    return math.floor(number * 10^decimals + 0.5) / 10^decimals
end

function Library:Create(className, properties)
    local instance = Instance.new(className)
    for property, value in pairs(properties) do
        if type(property) == "number" then
            if type(value) == "table" then
                local child = self:Create(value[1], value[2])
                child.Parent = instance
            end
        elseif property ~= "Parent" then
            local success, err = pcall(function()
                instance[property] = value
            end)
            if not success and property ~= "Children" then
                warn("[Nexus Vision] Failed to set property:", property, err)
            end
        end
    end
    return instance
end

--[=[ Theme System ]=]

function Library:SetTheme(theme)
    Library.Theme = theme
    for _, element in pairs(Library.Registry) do
        if element.UpdateTheme then
            element:UpdateTheme(theme)
        end
    end
end

function Library:GetTheme()
    return Library.Theme
end

--[=[ Animation System ]=]

function Library:Tween(object, properties, duration, easing, callback)
    duration = duration or 0.3
    easing = easing or Enum.EasingStyle.Quad
    local tweenInfo = TweenInfo.new(duration, easing, Enum.EasingDirection.Out)
    local tween = TweenService:Create(object, tweenInfo, properties)
    tween:Play()
    if callback then
        tween.Completed:Connect(callback)
    end
    table.insert(Library.Animations, tween)
    return tween
end

--[=[ Drag System ]=]

function Library:MakeDraggable(frame, dragHandle)
    dragHandle = dragHandle or frame
    local dragging = false
    local dragStart = nil
    local frameStart = nil

    dragHandle.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or
           input.UserInputType == Enum.UserInputType.Touch then
            dragging = true
            dragStart = input.Position
            frameStart = frame.Position
            input.Changed:Connect(function()
                if input.UserInputState == Enum.UserInputState.End then
                    dragging = false
                end
            end)
        end
    end)

    UserInputService.InputChanged:Connect(function(input)
        if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or
           input.UserInputType == Enum.UserInputType.Touch) then
            local delta = input.Position - dragStart
            frame.Position = UDim2.new(
                frameStart.X.Scale,
                frameStart.X.Offset + delta.X,
                frameStart.Y.Scale,
                frameStart.Y.Offset + delta.Y
            )
        end
    end)
end

--[=[ Window System ]=]

function Library:CreateWindow(options)
    options = options or {}
    local window = {
        Type = "Window",
        Title = options.Title or "Nexus Vision UI",
        Size = options.Size or UDim2.new(0, 800, 0, 600),
        Position = options.Position or UDim2.new(0.5, -400, 0.5, -300),
        MinSize = options.MinSize or Vector2.new(400, 300),
        Theme = options.Theme or Library.Theme,
        Tabs = {},
        Elements = {},
        Minimized = false,
        Closed = false,
    }

    local screenGui = Library:Create("ScreenGui", {
        Name = "NexusVision_" .. tostring(math.random(1000, 9999)),
        Parent = LocalPlayer:WaitForChild("PlayerGui"),
        DisplayOrder = 10,
        IgnoreGuiInset = options.IgnoreGuiInset or true,
    })

    window.Container = screenGui

    local mainFrame = Library:Create("Frame", {
        Name = "MainWindow",
        Size = window.Size,
        Position = window.Position,
        BackgroundColor3 = window.Theme.Background or Color3.fromRGB(10, 10, 15),
        BorderSizePixel = 0,
        ClipsDescendants = true,
        Parent = screenGui,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, window.Theme.CornerRadius or 8),
        Parent = mainFrame,
    })

    if window.Theme.ShadowEnabled ~= false then
        Library:Create("UIStroke", {
            Color = window.Theme.Border or Color3.fromRGB(42, 42, 78),
            Thickness = 1,
            Transparency = window.Theme.BorderTransparency or 0.5,
            Parent = mainFrame,
        })
    end

    -- Title Bar
    local titleBar = Library:Create("Frame", {
        Name = "TitleBar",
        Size = UDim2.new(1, 0, 0, 40),
        BackgroundColor3 = window.Theme.Surface or Color3.fromRGB(26, 26, 46),
        BorderSizePixel = 0,
        Parent = mainFrame,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, window.Theme.CornerRadius or 8),
        Parent = titleBar,
    })

    -- Top corner fix
    Library:Create("Frame", {
        Name = "TopCornerFix",
        Size = UDim2.new(1, 0, 0, 4),
        BackgroundColor3 = window.Theme.Surface or Color3.fromRGB(26, 26, 46),
        BorderSizePixel = 0,
        Position = UDim2.new(0, 0, 0, 36),
        Parent = mainFrame,
    })

    -- Title
    local title = Library:Create("TextLabel", {
        Name = "Title",
        Size = UDim2.new(1, -80, 1, 0),
        Position = UDim2.new(0, 12, 0, 0),
        BackgroundTransparency = 1,
        Text = window.Title,
        TextColor3 = window.Theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = window.Theme.TitleSize or 16,
        Font = window.Theme.Font or Enum.Font.GothamSemibold,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = titleBar,
    })

    -- Window Buttons
    local buttonSize = 16
    local buttonPadding = 6
    local currentX = -buttonSize - buttonPadding

    if options.CloseEnabled ~= false then
        local closeBtn = Library:Create("ImageButton", {
            Name = "CloseButton",
            Size = UDim2.new(0, buttonSize, 0, buttonSize),
            Position = UDim2.new(1, currentX, 0.5, -buttonSize / 2),
            BackgroundTransparency = 1,
            Image = "rbxassetid://10747313939",
            ImageColor3 = window.Theme.Error or Color3.fromRGB(239, 68, 68),
            Parent = titleBar,
        })
        window.CloseButton = closeBtn
        window.CloseButton.MouseButton1Click:Connect(function()
            window:Close()
        end)
        currentX -= buttonSize + buttonPadding
    end

    if options.MinimizeEnabled ~= false then
        local minBtn = Library:Create("ImageButton", {
            Name = "MinimizeButton",
            Size = UDim2.new(0, buttonSize, 0, buttonSize),
            Position = UDim2.new(1, currentX, 0.5, -buttonSize / 2),
            BackgroundTransparency = 1,
            Image = "rbxassetid://10747313939",
            ImageColor3 = window.Theme.Warning or Color3.fromRGB(245, 158, 11),
            Parent = titleBar,
        })
        window.MinimizeButton = minBtn
        minBtn.MouseButton1Click:Connect(function()
            window:ToggleMinimize()
        end)
        currentX -= buttonSize + buttonPadding
    end

    Library:MakeDraggable(mainFrame, titleBar)

    -- Tab Container
    local tabContainer = Library:Create("Frame", {
        Name = "TabContainer",
        Size = UDim2.new(1, 0, 0, 36),
        Position = UDim2.new(0, 0, 0, 40),
        BackgroundColor3 = window.Theme.Surface or Color3.fromRGB(26, 26, 46),
        BorderSizePixel = 0,
        Parent = mainFrame,
    })

    Library:Create("UIStroke", {
        Color = window.Theme.Border or Color3.fromRGB(42, 42, 78),
        Thickness = 1,
        Transparency = 0.7,
        Parent = tabContainer,
    })

    local tabList = Library:Create("ScrollingFrame", {
        Name = "TabList",
        Size = UDim2.new(1, -8, 1, 0),
        Position = UDim2.new(0, 4, 0, 0),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        ScrollBarThickness = 0,
        CanvasSize = UDim2.new(2, 0, 0, 0),
        ScrollingDirection = Enum.ScrollingDirection.X,
        Parent = tabContainer,
    })

    local tabLayout = Library:Create("UIListLayout", {
        FillDirection = Enum.FillDirection.Horizontal,
        HorizontalAlignment = Enum.HorizontalAlignment.Left,
        VerticalAlignment = Enum.VerticalAlignment.Center,
        SortOrder = Enum.SortOrder.LayoutOrder,
        Padding = UDim.new(0, 4),
        Parent = tabList,
    })

    window.MainFrame = mainFrame
    window.TabList = tabList
    window.TabContainer = tabContainer
    window.ContentContainer = nil

    -- Content Container
    local contentContainer = Library:Create("Frame", {
        Name = "ContentContainer",
        Size = UDim2.new(1, 0, 1, -76),
        Position = UDim2.new(0, 0, 0, 76),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        Parent = mainFrame,
    })

    window.ContentContainer = contentContainer

    -- Resize support
    if options.ResizeEnabled ~= false then
        local resizeHandle = Library:Create("Frame", {
            Name = "ResizeHandle",
            Size = UDim2.new(0, 8, 0, 8),
            Position = UDim2.new(1, -8, 1, -8),
            BackgroundColor3 = Color3.fromRGB(255, 255, 255),
            BackgroundTransparency = 0.8,
            BorderSizePixel = 0,
            Cursor = "SizeNWSE",
            Parent = mainFrame,
        })

        Library:Create("UICorner", {
            CornerRadius = UDim.new(1, 0),
            Parent = resizeHandle,
        })

        local resizing = false
        local resizeStart = nil
        local sizeStart = nil

        resizeHandle.InputBegan:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton1 then
                resizing = true
                resizeStart = input.Position
                sizeStart = mainFrame.Size
            end
        end)

        UserInputService.InputChanged:Connect(function(input)
            if resizing and input.UserInputType == Enum.UserInputType.MouseMovement then
                local delta = input.Position - resizeStart
                local newWidth = math.max(window.MinSize.X, sizeStart.X.Offset + delta.X)
                local newHeight = math.max(window.MinSize.Y, sizeStart.Y.Offset + delta.Y)
                mainFrame.Size = UDim2.new(0, newWidth, 0, newHeight)
            end
        end)

        UserInputService.InputEnded:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton1 then
                resizing = false
            end
        end)
    end

    -- Window Methods
    function window:AddTab(name)
        return Library:CreateTab(window, name)
    end

    function window:SelectTab(tab)
        for _, t in pairs(window.Tabs) do
            t:SetSelected(t == tab)
        end
        window.SelectedTab = tab
    end

    function window:ToggleMinimize()
        window.Minimized = not window.Minimized
        if window.Minimized then
            Library:Tween(mainFrame, {Size = UDim2.new(0, window.Size.X.Offset, 0, 40)}, 0.2)
            window.ContentContainer.Visible = false
        else
            Library:Tween(mainFrame, {Size = window.Size}, 0.2, nil, function()
                window.ContentContainer.Visible = true
            end)
        end
    end

    function window:Close()
        window.Closed = true
        Library:Tween(mainFrame, {BackgroundTransparency = 1}, 0.3, nil, function()
            screenGui:Destroy()
        end)
        for _, element in pairs(mainFrame:GetDescendants()) do
            if element:IsA("Frame") or element:IsA("TextLabel") or element:IsA("ImageButton") then
                Library:Tween(element, {BackgroundTransparency = 1}, 0.2)
            end
        end
    end

    function window:Destroy()
        screenGui:Destroy()
    end

    function window:SetSize(width, height)
        window.Size = UDim2.new(0, width, 0, height)
        Library:Tween(mainFrame, {Size = window.Size}, 0.3)
    end

    table.insert(Library.Elements, window)
    return window
end

--[=[ Tab System ]=]

function Library:CreateTab(window, name, icon)
    icon = icon or ""
    local tab = {
        Type = "Tab",
        Name = name,
        Window = window,
        Sections = {},
        Selected = false,
    }

    local tabButton = Library:Create("TextButton", {
        Name = "Tab_" .. name,
        Size = UDim2.new(0, 0, 0, 28),
        BackgroundTransparency = 0.85,
        BackgroundColor3 = window.Theme.Surface or Color3.fromRGB(30, 30, 50),
        Text = "",
        BorderSizePixel = 0,
        Parent = window.TabList,
        LayoutOrder = #window.Tabs,
    })

    local tabLabel = Library:Create("TextLabel", {
        Name = "TabLabel",
        Size = UDim2.new(1, -16, 1, 0),
        Position = UDim2.new(0, 8, 0, 0),
        BackgroundTransparency = 1,
        Text = name,
        TextColor3 = window.Theme.TextSecondary or Color3.fromRGB(160, 160, 180),
        TextSize = window.Theme.TabSize or 13,
        Font = window.Theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = tabButton,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, 4),
        Parent = tabButton,
    })

    -- Tab content
    local content = Library:Create("ScrollingFrame", {
        Name = "TabContent_" .. name,
        Size = UDim2.new(1, -12, 1, -8),
        Position = UDim2.new(0, 6, 0, 4),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        ScrollBarThickness = 4,
        ScrollBarImageColor3 = window.Theme.Accent or Color3.fromRGB(99, 102, 241),
        Visible = false,
        Parent = window.ContentContainer,
    })

    local contentLayout = Library:Create("UIListLayout", {
        FillDirection = Enum.FillDirection.Vertical,
        HorizontalAlignment = Enum.HorizontalAlignment.Left,
        SortOrder = Enum.SortOrder.LayoutOrder,
        Padding = UDim.new(0, 8),
        Parent = content,
    })

    Library:Create("UIPadding", {
        PaddingLeft = UDim.new(0, 4),
        PaddingRight = UDim.new(0, 4),
        PaddingTop = UDim.new(0, 4),
        PaddingBottom = UDim.new(0, 4),
        Parent = content,
    })

    tab.Content = content
    tab.Button = tabButton
    tab.Label = tabLabel

    tabButton.MouseButton1Click:Connect(function()
        window:SelectTab(tab)
    end)

    -- Tab Methods
    function tab:SetSelected(selected)
        tab.Selected = selected
        if selected then
            tabLabel.TextColor3 = window.Theme.Text or Color3.fromRGB(255, 255, 255)
            Library:Tween(tabButton, {BackgroundTransparency = 0.6}, 0.2)
            content.Visible = true
        else
            tabLabel.TextColor3 = window.Theme.TextSecondary or Color3.fromRGB(160, 160, 180)
            Library:Tween(tabButton, {BackgroundTransparency = 0.85}, 0.2)
            content.Visible = false
        end
    end

    function tab:AddSection(name)
        return Library:CreateSection(tab, name)
    end

    function tab:Destroy()
        content:Destroy()
        tabButton:Destroy()
    end

    table.insert(window.Tabs, tab)

    -- Auto select first tab
    if #window.Tabs == 1 then
        window:SelectTab(tab)
    end

    -- Update tab sizes
    for _, t in pairs(window.Tabs) do
        t.Button.Size = UDim2.new(0, 90, 0, 28)
    end

    return tab
end

--[=[ Section System ]=]

function Library:CreateSection(tab, name)
    local section = {
        Type = "Section",
        Name = name,
        Tab = tab,
        Elements = {},
    }

    local sectionFrame = Library:Create("Frame", {
        Name = "Section_" .. name,
        Size = UDim2.new(1, 0, 0, 30),
        BackgroundColor3 = tab.Window.Theme.Surface or Color3.fromRGB(25, 25, 45),
        BackgroundTransparency = 0.5,
        BorderSizePixel = 0,
        Parent = tab.Content,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, tab.Window.Theme.CornerRadius or 6),
        Parent = sectionFrame,
    })

    Library:Create("UIStroke", {
        Color = tab.Window.Theme.Border or Color3.fromRGB(30, 30, 50),
        Thickness = 1,
        Transparency = 0.8,
        Parent = sectionFrame,
    })

    local sectionTitle = Library:Create("TextLabel", {
        Name = "SectionTitle",
        Size = UDim2.new(1, -16, 0, 24),
        Position = UDim2.new(0, 8, 0, 6),
        BackgroundTransparency = 1,
        Text = name,
        TextColor3 = tab.Window.Theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = tab.Window.Theme.SectionSize or 14,
        Font = tab.Window.Theme.Font or Enum.Font.GothamSemibold,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = sectionFrame,
    })

    local sectionContent = Library:Create("Frame", {
        Name = "SectionContent",
        Size = UDim2.new(1, -16, 0, 0),
        Position = UDim2.new(0, 8, 0, 34),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        Parent = sectionFrame,
    })

    local layout = Library:Create("UIListLayout", {
        FillDirection = Enum.FillDirection.Vertical,
        HorizontalAlignment = Enum.HorizontalAlignment.Left,
        SortOrder = Enum.SortOrder.LayoutOrder,
        Padding = UDim.new(0, 6),
        Parent = sectionContent,
    })

    section.Frame = sectionFrame
    section.Content = sectionContent
    section.Layout = layout

    function section:AddButton(text, callback)
        return Library:CreateButton(section, text, callback)
    end

    function section:AddToggle(text, default, callback)
        return Library:CreateToggle(section, text, default, callback)
    end

    function section:AddSlider(text, min, max, default, callback)
        return Library:CreateSlider(section, text, min, max, default, callback)
    end

    function section:AddDropdown(text, options, default, callback)
        return Library:CreateDropdown(section, text, options, default, callback)
    end

    function section:AddTextbox(text, placeholder, callback)
        return Library:CreateTextbox(section, text, placeholder, callback)
    end

    function section:AddLabel(text)
        return Library:CreateLabel(section, text)
    end

    function section:AddParagraph(text, content)
        return Library:CreateParagraph(section, text, content)
    end

    function section:UpdateSize()
        local totalHeight = 38
        for _, child in pairs(sectionContent:GetChildren()) do
            if child:IsA("Frame") or child:IsA("TextLabel") then
                totalHeight = totalHeight + child.Size.Y.Offset + 6
            end
        end
        sectionFrame.Size = UDim2.new(1, 0, 0, totalHeight)
    end

    table.insert(section.Elements, section)
    return section
end

--[=[ Button System ]=]

function Library:CreateButton(section, text, callback)
    callback = callback or function() end
    local window = section.Tab.Window
    local theme = window.Theme

    local button = Library:Create("TextButton", {
        Name = "Button_" .. text,
        Size = UDim2.new(1, 0, 0, 32),
        BackgroundColor3 = theme.Accent or Color3.fromRGB(99, 102, 241),
        Text = "",
        BorderSizePixel = 0,
        Parent = section.Content,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, theme.CornerRadius or 4),
        Parent = button,
    })

    local label = Library:Create("TextLabel", {
        Name = "ButtonLabel",
        Size = UDim2.new(1, -16, 1, 0),
        Position = UDim2.new(0, 8, 0, 0),
        BackgroundTransparency = 1,
        Text = text,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = theme.ButtonSize or 13,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = button,
    })

    button.MouseButton1Click:Connect(callback)

    button.MouseEnter:Connect(function()
        Library:Tween(button, {BackgroundColor3 = theme.AccentHover or Color3.fromRGB(120, 120, 255)}, 0.15)
    end)

    button.MouseLeave:Connect(function()
        Library:Tween(button, {BackgroundColor3 = theme.Accent or Color3.fromRGB(99, 102, 241)}, 0.15)
    end)

    section:UpdateSize()
    return button
end

--[=[ Toggle System ]=]

function Library:CreateToggle(section, text, default, callback)
    default = default or false
    callback = callback or function() end
    local window = section.Tab.Window
    local theme = window.Theme
    local toggled = default

    local toggleFrame = Library:Create("Frame", {
        Name = "Toggle_" .. text,
        Size = UDim2.new(1, 0, 0, 28),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        Parent = section.Content,
    })

    local label = Library:Create("TextLabel", {
        Name = "ToggleLabel",
        Size = UDim2.new(1, -44, 1, 0),
        Position = UDim2.new(0, -4, 0, 0),
        BackgroundTransparency = 1,
        Text = text,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = theme.ToggleSize or 13,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = toggleFrame,
    })

    local toggleBg = Library:Create("Frame", {
        Name = "ToggleBackground",
        Size = UDim2.new(0, 36, 0, 18),
        Position = UDim2.new(1, -40, 0.5, -9),
        BackgroundColor3 = toggled and (theme.Success or Color3.fromRGB(34, 197, 94)) or Color3.fromRGB(60, 60, 80),
        BorderSizePixel = 0,
        Parent = toggleFrame,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(1, 0),
        Parent = toggleBg,
    })

    local toggleCircle = Library:Create("Frame", {
        Name = "ToggleCircle",
        Size = UDim2.new(0, 14, 0, 14),
        Position = UDim2.new(toggled and 0.55 or 0.05, 0, 0.5, -7),
        BackgroundColor3 = Color3.fromRGB(255, 255, 255),
        BorderSizePixel = 0,
        Parent = toggleBg,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(1, 0),
        Parent = toggleCircle,
    })

    local button = Library:Create("TextButton", {
        Name = "ToggleButton",
        Size = UDim2.new(1, 0, 1, 0),
        BackgroundTransparency = 1,
        Text = "",
        BorderSizePixel = 0,
        Parent = toggleFrame,
    })

    function toggleFrame:SetValue(value)
        toggled = value
        if toggled then
            Library:Tween(toggleBg, {BackgroundColor3 = theme.Success or Color3.fromRGB(34, 197, 94)}, 0.2)
            Library:Tween(toggleCircle, {Position = UDim2.new(0.55, 0, 0.5, -7)}, 0.2)
        else
            Library:Tween(toggleBg, {BackgroundColor3 = Color3.fromRGB(60, 60, 80)}, 0.2)
            Library:Tween(toggleCircle, {Position = UDim2.new(0.05, 0, 0.5, -7)}, 0.2)
        end
        callback(toggled)
    end

    button.MouseButton1Click:Connect(function()
        toggleFrame:SetValue(not toggled)
    end)

    section:UpdateSize()
    return toggleFrame
end

--[=[ Slider System ]=]

function Library:CreateSlider(section, text, min, max, default, callback)
    min = min or 0
    max = max or 100
    default = default or min
    callback = callback or function() end
    local window = section.Tab.Window
    local theme = window.Theme
    local value = default

    local sliderFrame = Library:Create("Frame", {
        Name = "Slider_" .. text,
        Size = UDim2.new(1, 0, 0, 44),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        Parent = section.Content,
    })

    local label = Library:Create("TextLabel", {
        Name = "SliderLabel",
        Size = UDim2.new(1, -50, 0, 18),
        Position = UDim2.new(0, 0, 0, 0),
        BackgroundTransparency = 1,
        Text = text,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = theme.SliderSize or 13,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = sliderFrame,
    })

    local valueLabel = Library:Create("TextLabel", {
        Name = "ValueLabel",
        Size = UDim2.new(0, 50, 0, 18),
        Position = UDim2.new(1, -50, 0, 0),
        BackgroundTransparency = 1,
        Text = tostring(math.floor(value)),
        TextColor3 = theme.Accent or Color3.fromRGB(99, 102, 241),
        TextSize = theme.SliderSize or 13,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Right,
        Parent = sliderFrame,
    })

    local rail = Library:Create("Frame", {
        Name = "SliderRail",
        Size = UDim2.new(1, 0, 0, 4),
        Position = UDim2.new(0, 0, 0, 24),
        BackgroundColor3 = Color3.fromRGB(40, 40, 60),
        BorderSizePixel = 0,
        Parent = sliderFrame,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(1, 0),
        Parent = rail,
    })

    local fill = Library:Create("Frame", {
        Name = "SliderFill",
        Size = UDim2.new((value - min) / (max - min), 0, 1, 0),
        BackgroundColor3 = theme.Accent or Color3.fromRGB(99, 102, 241),
        BorderSizePixel = 0,
        Parent = rail,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(1, 0),
        Parent = fill,
    })

    local knob = Library:Create("Frame", {
        Name = "SliderKnob",
        Size = UDim2.new(0, 12, 0, 12),
        Position = UDim2.new((value - min) / (max - min), -6, 0.5, -6),
        BackgroundColor3 = Color3.fromRGB(255, 255, 255),
        BorderSizePixel = 0,
        Parent = rail,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(1, 0),
        Parent = knob,
    })

    local dragging = false
    local function updateSlider(inputPos)
        local pos = inputPos - rail.AbsolutePosition.X
        local percent = math.clamp(pos / rail.AbsoluteSize.X, 0, 1)
        value = min + (max - min) * percent
        fill.Size = UDim2.new(percent, 0, 1, 0)
        knob.Position = UDim2.new(percent, -6, 0.5, -6)
        valueLabel.Text = tostring(math.floor(value))
        callback(value)
    end

    rail.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            updateSlider(input.Position)
        end
    end)

    UserInputService.InputChanged:Connect(function(input)
        if dragging and input.UserInputType == Enum.UserInputType.MouseMovement then
            updateSlider(input.Position)
        end
    end)

    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = false
        end
    end)

    section:UpdateSize()
    return sliderFrame
end

--[=[ Dropdown System ]=]

function Library:CreateDropdown(section, text, options, default, callback)
    default = default or ""
    callback = callback or function() end
    local window = section.Tab.Window
    local theme = window.Theme
    local selected = default
    local open = false

    local dropdownFrame = Library:Create("Frame", {
        Name = "Dropdown_" .. text,
        Size = UDim2.new(1, 0, 0, 28),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        Parent = section.Content,
    })

    local label = Library:Create("TextLabel", {
        Name = "DropdownLabel",
        Size = UDim2.new(0, 120, 1, 0),
        Position = UDim2.new(0, -4, 0, 0),
        BackgroundTransparency = 1,
        Text = text,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = theme.DropdownSize or 13,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = dropdownFrame,
    })

    local button = Library:Create("TextButton", {
        Name = "DropdownButton",
        Size = UDim2.new(0, 140, 0, 24),
        Position = UDim2.new(1, -144, 0.5, -12),
        BackgroundColor3 = Color3.fromRGB(30, 30, 50),
        Text = "",
        BorderSizePixel = 0,
        Parent = dropdownFrame,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, 4),
        Parent = button,
    })

    local buttonText = Library:Create("TextLabel", {
        Name = "DropdownText",
        Size = UDim2.new(1, -20, 1, 0),
        Position = UDim2.new(0, 6, 0, 0),
        BackgroundTransparency = 1,
        Text = selected ~= "" and selected or "Select...",
        TextColor3 = theme.TextSecondary or Color3.fromRGB(160, 160, 180),
        TextSize = 12,
        Font = Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = button,
    })

    local arrow = Library:Create("TextLabel", {
        Name = "DropdownArrow",
        Size = UDim2.new(0, 14, 1, 0),
        Position = UDim2.new(1, -18, 0, 0),
        BackgroundTransparency = 1,
        Text = "▼",
        TextColor3 = theme.TextSecondary or Color3.fromRGB(160, 160, 180),
        TextSize = 8,
        Font = Enum.Font.Gotham,
        Parent = button,
    })

    local dropdownList = Library:Create("ScrollingFrame", {
        Name = "DropdownList",
        Size = UDim2.new(0, 140, 0, 0),
        Position = UDim2.new(1, -144, 1, 2),
        BackgroundColor3 = Color3.fromRGB(25, 25, 45),
        BorderSizePixel = 0,
        Visible = false,
        ScrollBarThickness = 2,
        ZIndex = 10,
        Parent = dropdownFrame,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, 4),
        Parent = dropdownList,
    })

    Library:Create("UIStroke", {
        Color = theme.Border or Color3.fromRGB(30, 30, 50),
        Thickness = 1,
        Transparency = 0.5,
        Parent = dropdownList,
    })

    local listLayout = Library:Create("UIListLayout", {
        SortOrder = Enum.SortOrder.LayoutOrder,
        Padding = UDim.new(0, 2),
        Parent = dropdownList,
    })

    local optionButtons = {}
    for _, option in pairs(options) do
        local optButton = Library:Create("TextButton", {
            Name = "Option_" .. option,
            Size = UDim2.new(1, -4, 0, 24),
            Position = UDim2.new(0, 2, 0, 0),
            BackgroundTransparency = 0.9,
            Text = "",
            BorderSizePixel = 0,
            Parent = dropdownList,
            LayoutOrder = #optionButtons + 1,
        })

        Library:Create("UICorner", {
            CornerRadius = UDim.new(0, 3),
            Parent = optButton,
        })

        local optLabel = Library:Create("TextLabel", {
            Name = "OptionLabel",
            Size = UDim2.new(1, -8, 1, 0),
            Position = UDim2.new(0, 4, 0, 0),
            BackgroundTransparency = 1,
            Text = option,
            TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
            TextSize = 12,
            Font = Enum.Font.Gotham,
            TextXAlignment = Enum.TextXAlignment.Left,
            Parent = optButton,
        })

        optButton.MouseButton1Click:Connect(function()
            selected = option
            buttonText.Text = option
            buttonText.TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255)
            open = false
            dropdownList.Visible = false
            callback(option)
        end)

        table.insert(optionButtons, optButton)
    end

    dropdownList.CanvasSize = UDim2.new(0, 0, 0, #optionButtons * 26 + 4)
    local listHeight = math.min(#optionButtons * 26 + 4, 180)
    dropdownList.Size = UDim2.new(0, 140, 0, listHeight)

    button.MouseButton1Click:Connect(function()
        open = not open
        dropdownList.Visible = open
    end)

    UserInputService.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            if open and not dropdownFrame:IsAncestorOf(game:GetService("GuiService").SelectedObject) then
                open = false
                dropdownList.Visible = false
            end
        end
    end)

    section:UpdateSize()
    return dropdownFrame
end

--[=[ Textbox System ]=]

function Library:CreateTextbox(section, text, placeholder, callback)
    placeholder = placeholder or "Enter text..."
    callback = callback or function() end
    local window = section.Tab.Window
    local theme = window.Theme

    local textboxFrame = Library:Create("Frame", {
        Name = "Textbox_" .. text,
        Size = UDim2.new(1, 0, 0, 28),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        Parent = section.Content,
    })

    local label = Library:Create("TextLabel", {
        Name = "TextboxLabel",
        Size = UDim2.new(0, 120, 1, 0),
        Position = UDim2.new(0, -4, 0, 0),
        BackgroundTransparency = 1,
        Text = text,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = theme.TextboxSize or 13,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = textboxFrame,
    })

    local textbox = Library:Create("TextBox", {
        Name = "TextBoxInput",
        Size = UDim2.new(0, 140, 0, 24),
        Position = UDim2.new(1, -144, 0.5, -12),
        BackgroundColor3 = Color3.fromRGB(20, 20, 40),
        Text = "",
        PlaceholderText = placeholder,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        PlaceholderColor3 = theme.TextSecondary or Color3.fromRGB(100, 100, 120),
        TextSize = 12,
        Font = Enum.Font.Gotham,
        ClearTextOnFocus = false,
        BorderSizePixel = 0,
        Parent = textboxFrame,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, 4),
        Parent = textbox,
    })

    Library:Create("UIStroke", {
        Color = theme.Border or Color3.fromRGB(30, 30, 50),
        Thickness = 1,
        Transparency = 0.5,
        Parent = textbox,
    })

    textbox.FocusLost:Connect(function()
        callback(textbox.Text)
    end)

    section:UpdateSize()
    return textbox
end

--[=[ Label System ]=]

function Library:CreateLabel(section, text)
    local window = section.Tab.Window
    local theme = window.Theme

    local label = Library:Create("TextLabel", {
        Name = "Label_" .. text,
        Size = UDim2.new(1, 0, 0, 20),
        BackgroundTransparency = 1,
        Text = text,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = theme.LabelSize or 13,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = section.Content,
    })

    section:UpdateSize()
    return label
end

--[=[ Paragraph System ]=]

function Library:CreateParagraph(section, title, content)
    content = content or ""
    local window = section.Tab.Window
    local theme = window.Theme

    local paragraphFrame = Library:Create("Frame", {
        Name = "Paragraph_" .. title,
        Size = UDim2.new(1, 0, 0, 40),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        Parent = section.Content,
    })

    local paragraphLabel = Library:Create("TextLabel", {
        Name = "ParagraphTitle",
        Size = UDim2.new(1, 0, 0, 18),
        BackgroundTransparency = 1,
        Text = title,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = theme.ParagraphTitleSize or 13,
        Font = theme.Font or Enum.Font.GothamSemibold,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = paragraphFrame,
    })

    local paragraphContent = Library:Create("TextLabel", {
        Name = "ParagraphContent",
        Size = UDim2.new(1, 0, 0, 20),
        Position = UDim2.new(0, 0, 0, 20),
        BackgroundTransparency = 1,
        Text = content,
        TextColor3 = theme.TextSecondary or Color3.fromRGB(160, 160, 180),
        TextSize = theme.ParagraphSize or 12,
        Font = theme.Font or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        TextWrapped = true,
        RichText = true,
        Parent = paragraphFrame,
    })

    section:UpdateSize()
    return paragraphFrame
end

--[=[ Notification System ]=]

function Library:CreateNotification(options)
    options = options or {}
    local title = options.Title or "Notification"
    local message = options.Message or ""
    local duration = options.Duration or 3
    local notifType = options.Type or "info"
    local theme = options.Theme or Library.Theme

    local notifColors = {
        info = theme.Accent or Color3.fromRGB(99, 102, 241),
        success = theme.Success or Color3.fromRGB(34, 197, 94),
        error = theme.Error or Color3.fromRGB(239, 68, 68),
        warning = theme.Warning or Color3.fromRGB(245, 158, 11),
    }

    local screenGui = Library:Create("ScreenGui", {
        Name = "NotificationGui",
        Parent = LocalPlayer:WaitForChild("PlayerGui"),
        DisplayOrder = 100,
        IgnoreGuiInset = true,
    })

    local notifFrame = Library:Create("Frame", {
        Name = "Notification",
        Size = UDim2.new(0, 320, 0, 60),
        Position = UDim2.new(1, 20, 0, 20),
        BackgroundColor3 = theme.Surface or Color3.fromRGB(25, 25, 45),
        BorderSizePixel = 0,
        Parent = screenGui,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, theme.CornerRadius or 6),
        Parent = notifFrame,
    })

    Library:Create("UIStroke", {
        Color = notifColors[notifType] or notifColors.info,
        Thickness = 1,
        Transparency = 0.3,
        Parent = notifFrame,
    })

    local colorBar = Library:Create("Frame", {
        Name = "ColorBar",
        Size = UDim2.new(0, 4, 1, 0),
        BackgroundColor3 = notifColors[notifType] or notifColors.info,
        BorderSizePixel = 0,
        Parent = notifFrame,
    })

    Library:Create("UICorner", {
        CornerRadius = UDim.new(0, 2),
        Parent = colorBar,
    })

    local notifTitle = Library:Create("TextLabel", {
        Name = "NotifTitle",
        Size = UDim2.new(1, -20, 0, 18),
        Position = UDim2.new(0, 14, 0, 6),
        BackgroundTransparency = 1,
        Text = title,
        TextColor3 = theme.Text or Color3.fromRGB(255, 255, 255),
        TextSize = 13,
        Font = Enum.Font.GothamSemibold,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = notifFrame,
    })

    local notifMessage = Library:Create("TextLabel", {
        Name = "NotifMessage",
        Size = UDim2.new(1, -20, 0, 30),
        Position = UDim2.new(0, 14, 0, 26),
        BackgroundTransparency = 1,
        Text = message,
        TextColor3 = theme.TextSecondary or Color3.fromRGB(160, 160, 180),
        TextSize = 11,
        Font = Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left,
        TextWrapped = true,
        Parent = notifFrame,
    })

    -- Animate in
    Library:Tween(notifFrame, {Position = UDim2.new(1, -340, 0, 20)}, 0.3)

    -- Animate out after duration
    task.delay(duration, function()
        Library:Tween(notifFrame, {Position = UDim2.new(1, 20, 0, 20)}, 0.3, nil, function()
            screenGui:Destroy()
        end)
    end)

    -- Close on click
    notifFrame.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            Library:Tween(notifFrame, {Position = UDim2.new(1, 20, 0, 20)}, 0.2, nil, function()
                screenGui:Destroy()
            end)
        end
    end)
end

--[=[ Flag System ]=]

function Library:CreateFlag(name, default)
    Library.Flags[name] = default
    return {
        Name = name,
        Value = default,
        SetValue = function(self, value)
            Library.Flags[name] = value
            self.Value = value
        end,
        GetValue = function()
            return Library.Flags[name]
        end
    }
end

--[=[ Cleanup System ]=]

function Library:Unload()
    for _, connection in pairs(Library.Connections) do
        connection:Disconnect()
    end
    for _, animation in pairs(Library.Animations) do
        animation:Cancel()
    end
    for _, element in pairs(Library.Elements) do
        if element.Destroy then
            element:Destroy()
        end
    end
    Library.Elements = {}
    Library.Animations = {}
    Library.Connections = {}
    Library.Registry = {}
    Library.Flags = {}
end

--[=[ Default Theme ]=]

Library:SetTheme({
    Background = Color3.fromRGB(10, 10, 15),
    Surface = Color3.fromRGB(26, 26, 46),
    Text = Color3.fromRGB(255, 255, 255),
    TextSecondary = Color3.fromRGB(160, 160, 184),
    Accent = Color3.fromRGB(26, 26, 46),
    AccentHover = Color3.fromRGB(56, 56, 76),
    Error = Color3.fromRGB(239, 68, 68),
    Success = Color3.fromRGB(34, 197, 94),
    Warning = Color3.fromRGB(245, 158, 11),
    Border = Color3.fromRGB(42, 42, 78),
    Font = Enum.Font.Gotham,
    CornerRadius = 8,
    TitleSize = 16,
    TabSize = 13,
    SectionSize = 14,
    ButtonSize = 13,
    ToggleSize = 13,
    SliderSize = 13,
    DropdownSize = 13,
    TextboxSize = 13,
    LabelSize = 13,
    ParagraphTitleSize = 13,
    ParagraphSize = 12,
    ShadowEnabled = true,
    BorderTransparency = 0.5,
})

return Library
